name: Run Script with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Script in Docker Container
        uses: docker://andsande/prefect:latest
        with:
          entrypoint: "/bin/bash"
          args: "-c 'python /path/to/your/script.py'"
