name: Run Python Script from GitHub Repo in Docker

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Run the Docker container
      - name: Run script in Docker container
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: |
          docker run --shm-size=1g --memory=2g --cpus=2 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            andsande/prefect:latest \
            python tesla.py
      