name: Run Python Script from GitHub Repo in Docker

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Run the Docker container
      - name: Run script in Docker container
        run: |
          docker run \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            andsande/prefect:latest \
            python audi.py
