name: Sogndal kulturhus
on:
  workflow_dispatch:
  schedule: 
    - cron: "0 7 * * 0"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Checkout the private repository code
      - name: Checkout private repository code
        uses: actions/checkout@v2
        with:
          repository: and-sande/Default  # Replace with your private repo details
          token: ${{ secrets.PAT_TOKEN }}  # Ensure PAT_TOKEN is correctly set in your secrets
          path: private-repo       

      # Run the Docker container
      - name: Run script in Docker container
        run: |
          docker run --shm-size=1g --memory=2g --cpus=2 \
            -e PREFECT_API_KEY=${{ secrets.PREFECT_API_KEY }} \
            -e PREFECT_API_URL=${{ secrets.PREFECT_API_URL }} \
            -e KOYEB_DB=${{ secrets.KOYEB_DB }} \
            -e PYTHONANYWHERE_USERNAME=${{ secrets.PYTHONANYWHERE_USERNAME }} \
            -e PYTHONANYWHERE_API=${{ secrets.PYTHONANYWHERE_API }} \
            -e ELBILSTATS_FTP_USERNAME=${{ secrets.ELBILSTATS_FTP_USERNAME }} \
            -e ELBILSTATS_FTP_PASSWORD=${{ secrets.ELBILSTATS_FTP_PASSWORD }} \
            -v ${{ github.workspace }}:/workspace \
            -v ${{ github.workspace }}/private-repo:/private-repo \
            -w /workspace \
            andsande/prefect:latest \
            bash -c "
              apt-get update &&
              apt-get install -y wget libx11-xcb1 libdbus-1-3 libxcomposite1 libxdamage1 libxrandr2 libgtk-3-0 libasound2 libnss3 libxss1 libxtst6 fonts-liberation libappindicator3-1 libxshmfence1 xdg-utils &&
              wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - &&
              sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google-chrome.list' &&
              apt-get update &&
              apt-get install -y google-chrome-stable &&
              google-chrome --version &&
              pip install undetected-chromedriver playwright psycopg2-binary &&
              playwright install &&
              python '/private-repo/API_code/sogndal_kulturhus.py'
            "
